### ISSUE TITLE
No Section 7 present

### ISSUE THREAD

**Issue by NiharikaAtTR** [PacktPublishing/Learn-Spring-Boot-in-100-Steps---Beginner-to-Expert#2]
Hi,
I went through the file created especially for folks new to SpringBoot. I saw you had mentioned that folks had to first go through Section 
7
Unfortunately I am unable to see a section 7

**Comment by Sonakshis** [comment]
Hi!
Section 7 files are available here: https://github.com/PacktPublishing/Learn-Spring-Boot-in-100-Steps---Beginner-to-Expert/tree/master/07.spring-framework-in-10-steps
Happy learning!
